name: Publish Sheep Dog Test Release

on:
  workflow_dispatch:
permissions:
  contents: write
  packages: write

jobs:
  sheep-dog-test:
    uses: farhan5248/sheep-dog-ops/.github/workflows/maven-release.yml@main
    with:
      project: 'sheep-dog-test'
      plugin: 'Maven'
    secrets: inherit

  sheep-dog-xtext-plugin:
    needs: [sheep-dog-test]
    uses: farhan5248/sheep-dog-ops/.github/workflows/maven-release.yml@main
    with:
      project: 'sheepdogxtextplugin.parent'
      plugin: 'Sheep'
    secrets: inherit
  
  sheep-dog-dev:
    needs: [sheep-dog-xtext-plugin]
    uses: farhan5248/sheep-dog-ops/.github/workflows/maven-release.yml@main
    with:
      project: 'sheep-dog-dev'
      plugin: 'Maven'
    secrets: inherit

  sheep-dog-dev-maven-plugin:
    needs: [sheep-dog-dev]
    uses: farhan5248/sheep-dog-ops/.github/workflows/maven-release.yml@main
    with:
      project: 'sheep-dog-dev-maven-plugin'
      plugin: 'Maven'
    secrets: inherit    
    
  merge-into-develop:
    needs: [sheep-dog-dev-maven-plugin]
    uses: farhan5248/sheep-dog-ops/.github/workflows/merge.yml@main
    with:
      source: 'main'
      target: 'develop'
    secrets: inherit      
